### ISSUE TITLE
data persistence locations for bind mounts

### ISSUE THREAD

**Issue by brainchild0** [gcavalcante8808/docker-krb5-server#7]
I am targeting a container from this image to a Synology device running DiskStation Manager (DSM). The Docker system in DSM is rather restrictive compared to a general Docker installation. These restrictions include limitations on persistent volumes. Saving volumes beyond the life a specific container is not possible. Rather, such persistence is limited to bind mounts. 

The documentation for many Docker images includes a list of locations where data might be modified over the life of the container (whether manually or through the container processes). This information allows the administrator to bind external files or directories to such locations when deploying the container (thus preventing the new versions of files from being saved  inside any container volumes).

I would find it very helpful to have a list of all locations that administrators should consider for data persistence in containers from this project.

**Comment by gcavalcante8808** [comment]
Oh Hi @brainchild0 , normally for docker projects, I search for `VOLUME` on the Dockerfile as a hint where the data is persistent.

Is this useful enough for your case?

**Comment by gcavalcante8808** [comment]
Fixed by https://github.com/gcavalcante8808/docker-krb5-server/pull/14.
